server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cth_screen?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.driver.entity

